package hanto.studentramnur.gamma;

import junit.framework.TestCase;

/**
 * The class <code>GammaHantoTestGameTest</code> contains tests for the class
 * {@link <code>GammaHantoTestGame</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/28/14 11:29 AM
 *
 * @author srramadan
 *
 * @version $Revision$
 */
public class GammaHantoGameTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public GammaHantoGameTest(String name) {
		super(name);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = hanto.studentramnur.delta
 * package.sourceFolder = Hanto/test
 * superclassType = junit.framework.TestCase
 * testCase = GammaHantoTestGameTest
 * testClassType = hanto.studentramnur.gamma.GammaHantoTestGame
 */